### ISSUE TITLE
Minor issue -> loose indentation

### ISSUE THREAD

**Issue by Yousha** [YashasSamaga/I-ZCMD#1]
i-zcmd 0.2.2.1

E:\SA-MP server\pawno\include\izcmd.inc(93) : warning 217: loose indentation
E:\SA-MP server\pawno\include\izcmd.inc(97) : warning 217: loose indentation
E:\SA-MP server\pawno\include\izcmd.inc(99) : warning 217: loose indentation
E:\SA-MP server\pawno\include\izcmd.inc(100) : warning 217: loose indentation

I know it can be solved in GM/FS, but i think it's better to solve it in izcmd..
Maybe by defing 'tabsize' @ top of file, and undefing it @ end of file.

**Comment by YashasSamaga** [comment]
Fixed the indentations.
