### ISSUE TITLE
Detection of other system commands

### ISSUE THREAD

**Issue by AbyssMorgan** [YashasSamaga/I-ZCMD#2]
Hello, could you include upgrade of the rule.

#if defined _I_ZCMD_INCLUDED_V0_2_2_2_
	#endinput
#endif
#define _I_ZCMD_INCLUDED
#define _I_ZCMD_INCLUDED_V0_2_2_2_

#if defined CMD
	#error Detected another command system
#endif

**Comment by YashasSamaga** [comment]
Is it really needed? I would want to keep the include as small as possible :P

**Comment by AbyssMorgan** [comment]
It's about too many system commands which recently appears.
You are not needed, but it only control the compilation.

**Comment by YashasSamaga** [comment]
Such a case would probably never happen. Even if it did, the compiler wont let you compile because there would be two instances of OnPlayerCommandText. iZCMD does not hook the callback.

**Comment by AbyssMorgan** [comment]
Detection another command system never hurt anyone: D

**Comment by YashasSamaga** [comment]
will add in next update!
